#+auto_tangle: nil

*org-mode* 强大、综合、可拓展性极强的笔记系统
  
* org 和核心包
- org-cite and  org-citar
- org-babel
- +org-element+
- 美化：org-super-agenda org-modern / org-superstar
- deft / consult-notes
  
  冷门：
- org-attach
* org-mode 画图
* the academic org-mode
** org-cite org-citar  zotero与org-roam协作
#+begin_src emacs-lisp :tangle yes
    ;;;cite
    ;; (setq org-cite-global-bibliography '("~/references.bib"))
    ;; (setq org-cite-insert-processor 'citar)   ;; 可选，用 citar 来补全
    ;; (setq org-cite-follow-processor 'citar)
  (use-package oc
    :ensure nil  
    :config
    (setq org-cite-global-bibliography '("~/Documents/references.bib"))
    ;; 导出后端：csl 支持 APA/Chicago 等样式
    (setq org-cite-export-processors
          '((latex . (biblatex))         ;; 导出 PDF 用 biblatex
            (t     . (csl "apa.csl")))))  ;; 其他格式用 CSL/APA

  

(use-package citar-embark
  :ensure t
  :after (citar embark)
  :config
  (citar-embark-mode))


(use-package citar-org-roam
  :ensure t
  :after (citar org-roam)
  :custom
  ;; 对应你的 "R" Academic 模板
  (citar-org-roam-capture-template-key "R")

  ;; 笔记文件名格式，与你现有模板保持一致
  (citar-org-roam-note-title-template "${title}")

  :config
  (citar-org-roam-mode)

  ;; 自定义创建笔记时的额外属性（写入 front matter）
  (setq citar-org-roam-template-fields
        '((:citar-title    "title")
          (:citar-author   "author")
          (:citar-date     "date")
          (:citar-type     "type")
          (:citar-citekey  "citekey"))))
    
#+end_src
*** 使用方法
- C-c b b
- C-c b n
- o
- e
- r
*** 依赖
zotero
embark（可选）
在org-roam的配置里修改模板
** org latex
#+begin_src emacs-lisp :tangle yes

  (use-package auctex
    :defer t
    :ensure t
    )

  (use-package tex
    :ensure auctex
    :config
    ;; 自动解析文件
    (setq TeX-auto-save t)
    (setq TeX-parse-self t)

    ;; 多文件文档支持
    (setq-default TeX-master nil)

    ;; 使用 PDF 模式
    (setq TeX-PDF-mode t)

    ;; 启用折叠模式
    (add-hook 'LaTeX-mode-hook 'TeX-fold-mode)

    ;; 启用数学模式预览
    (add-hook 'LaTeX-mode-hook 'LaTeX-math-mode)

    ;; 启用行号
    (add-hook 'LaTeX-mode-hook 'display-line-numbers-mode))






  (use-package org-fragtog
    :hook (org-mode . org-fragtog-mode))  
  (use-package cdlatex 
    :hook (org-mode . org-cdlatex-mode))




  (provide 'my-org-mode)

              ;;; my-org-mode.el ends here
#+end_src

6. 编译快捷键
快捷键功能C-c C-c编译（自动选择命令）C-c C-v查看 PDFC-c C-l显示编译日志C-c C-k清理临时文件
依赖： =sudo pacman -S texlive-meta otf-ipaexfont=
依赖检查
#+begin_src bash
  lualatex --version
  tlmgr --version
#+end_src
*** org mode 里快速输入latex
todo
=C-c {=

*** latex在org mode里的使用
在 Org-mode 里用 LaTeX 非常自然，分两部分：

**** 数学公式

*行内公式*

质能方程 $E = mc^2$ 是物理学基础。


*独立公式块*
#+begin_src latex
  \begin{equation}
    \int_{-\infty}^{\infty} e^{-x^2} dx = \sqrt{\pi}
  \end{equation}
#+end_src

*对齐多行公式*
\begin{align}
f(x) &= x^2 + 2x + 1 \\
     &= (x+1)^2
\end{align}

*预览公式* （在 Emacs 里显示渲染效果）：
```
C-c C-x C-l   预览光标处/选中区域的公式
C-c C-x C-l   再按一次取消预览
```

全局预览所有公式在 `init.el` 里加：
```elisp
(add-hook 'org-mode-hook 'org-fragtog-mode)  ; 需要装 org-fragtog 包
;; 光标离开公式时自动渲染，进入时自动还原为源码
```

---

## 图表（用 Babel 代码块）

**直接插入 TikZ 图**：
````org
#+begin_src latex :file output.png :packages '(("" "tikz")) :exports results
\begin{tikzpicture}
  \draw[->] (0,0) -- (2,0) node[right] {$x$};
  \draw[->] (0,0) -- (0,2) node[above] {$y$};
  \draw[blue, thick] (0,0) -- (1,1) -- (2,0);
\end{tikzpicture}
#+end_src
````

**用 gnuplot 画函数图**：
````org
#+begin_src gnuplot :file plot.png :exports results
set title "sin(x)"
plot sin(x) with lines
#+end_src
````

执行代码块：`C-c C-c`，图片会自动插入文档。

需要在 `init.el` 启用 Babel：
```elisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((latex . t)
   (gnuplot . t)))
```

---

## 导出为 PDF

文件头部加：
#+begin_src 
  #+LATEX_COMPILER: lualatex
#+LATEX_CLASS: article

# 日语文档用：
#+LATEX_COMPILER: lualatex
#+LATEX_CLASS: jlreq
#+LATEX_HEADER: \usepackage{luatexja}
#+end_src



然后 `C-c C-e l p` 直接导出 PDF。


*推荐装的辅助包*


=cdlatex= 很好用，比如输入 =\int= 再按 =Tab= 自动补全积分模板。
